# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/element.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/element.proto',
  package='braggle',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16protobuf/element.proto\x12\x07\x62raggle\"f\n\nAttributes\x12+\n\x04misc\x18\x01 \x03(\x0b\x32\x1d.braggle.Attributes.MiscEntry\x1a+\n\tMiscEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"c\n\x03Tag\x12\x0f\n\x07tagname\x18\x01 \x01(\t\x12\'\n\nattributes\x18\x02 \x01(\x0b\x32\x13.braggle.Attributes\x12\"\n\x08\x63hildren\x18\x03 \x03(\x0b\x32\x10.braggle.Element\"U\n\x07\x45lement\x12\r\n\x03ref\x18\x01 \x01(\tH\x00\x12\x0e\n\x04text\x18\x02 \x01(\tH\x00\x12\x1b\n\x03tag\x18\x03 \x01(\x0b\x32\x0c.braggle.TagH\x00\x42\x0e\n\x0c\x65lement_kind\"\xb7\x01\n\x12PartialServerState\x12\x10\n\x08timestep\x18\x01 \x01(\x03\x12\x0f\n\x07root_id\x18\x02 \x01(\t\x12;\n\x08\x65lements\x18\x03 \x03(\x0b\x32).braggle.PartialServerState.ElementsEntry\x1a\x41\n\rElementsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.braggle.Element:\x02\x38\x01\"%\n\x0bPollRequest\x12\x16\n\x0esince_timestep\x18\x01 \x01(\x03\":\n\x0cPollResponse\x12*\n\x05state\x18\x01 \x01(\x0b\x32\x1b.braggle.PartialServerState\" \n\nClickEvent\x12\x12\n\nelement_id\x18\x01 \x01(\t\"3\n\x0eTextInputEvent\x12\x12\n\nelement_id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"v\n\x0bInteraction\x12$\n\x05\x63lick\x18\x01 \x01(\x0b\x32\x13.braggle.ClickEventH\x00\x12-\n\ntext_input\x18\x02 \x01(\x0b\x32\x17.braggle.TextInputEventH\x00\x42\x12\n\x10interaction_kind\"?\n\x12InteractionRequest\x12)\n\x0binteraction\x18\x01 \x01(\x0b\x32\x14.braggle.Interaction\"\x15\n\x13InteractionResponseb\x06proto3')
)




_ATTRIBUTES_MISCENTRY = _descriptor.Descriptor(
  name='MiscEntry',
  full_name='braggle.Attributes.MiscEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='braggle.Attributes.MiscEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='braggle.Attributes.MiscEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=137,
)

_ATTRIBUTES = _descriptor.Descriptor(
  name='Attributes',
  full_name='braggle.Attributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='misc', full_name='braggle.Attributes.misc', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ATTRIBUTES_MISCENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=137,
)


_TAG = _descriptor.Descriptor(
  name='Tag',
  full_name='braggle.Tag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tagname', full_name='braggle.Tag.tagname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attributes', full_name='braggle.Tag.attributes', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='children', full_name='braggle.Tag.children', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=238,
)


_ELEMENT = _descriptor.Descriptor(
  name='Element',
  full_name='braggle.Element',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ref', full_name='braggle.Element.ref', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='braggle.Element.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='braggle.Element.tag', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='element_kind', full_name='braggle.Element.element_kind',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=240,
  serialized_end=325,
)


_PARTIALSERVERSTATE_ELEMENTSENTRY = _descriptor.Descriptor(
  name='ElementsEntry',
  full_name='braggle.PartialServerState.ElementsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='braggle.PartialServerState.ElementsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='braggle.PartialServerState.ElementsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=511,
)

_PARTIALSERVERSTATE = _descriptor.Descriptor(
  name='PartialServerState',
  full_name='braggle.PartialServerState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestep', full_name='braggle.PartialServerState.timestep', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='root_id', full_name='braggle.PartialServerState.root_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='elements', full_name='braggle.PartialServerState.elements', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PARTIALSERVERSTATE_ELEMENTSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=511,
)


_POLLREQUEST = _descriptor.Descriptor(
  name='PollRequest',
  full_name='braggle.PollRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='since_timestep', full_name='braggle.PollRequest.since_timestep', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=513,
  serialized_end=550,
)


_POLLRESPONSE = _descriptor.Descriptor(
  name='PollResponse',
  full_name='braggle.PollResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='braggle.PollResponse.state', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=552,
  serialized_end=610,
)


_CLICKEVENT = _descriptor.Descriptor(
  name='ClickEvent',
  full_name='braggle.ClickEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='element_id', full_name='braggle.ClickEvent.element_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=612,
  serialized_end=644,
)


_TEXTINPUTEVENT = _descriptor.Descriptor(
  name='TextInputEvent',
  full_name='braggle.TextInputEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='element_id', full_name='braggle.TextInputEvent.element_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='braggle.TextInputEvent.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=646,
  serialized_end=697,
)


_INTERACTION = _descriptor.Descriptor(
  name='Interaction',
  full_name='braggle.Interaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='click', full_name='braggle.Interaction.click', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text_input', full_name='braggle.Interaction.text_input', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='interaction_kind', full_name='braggle.Interaction.interaction_kind',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=699,
  serialized_end=817,
)


_INTERACTIONREQUEST = _descriptor.Descriptor(
  name='InteractionRequest',
  full_name='braggle.InteractionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='interaction', full_name='braggle.InteractionRequest.interaction', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=819,
  serialized_end=882,
)


_INTERACTIONRESPONSE = _descriptor.Descriptor(
  name='InteractionResponse',
  full_name='braggle.InteractionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=884,
  serialized_end=905,
)

_ATTRIBUTES_MISCENTRY.containing_type = _ATTRIBUTES
_ATTRIBUTES.fields_by_name['misc'].message_type = _ATTRIBUTES_MISCENTRY
_TAG.fields_by_name['attributes'].message_type = _ATTRIBUTES
_TAG.fields_by_name['children'].message_type = _ELEMENT
_ELEMENT.fields_by_name['tag'].message_type = _TAG
_ELEMENT.oneofs_by_name['element_kind'].fields.append(
  _ELEMENT.fields_by_name['ref'])
_ELEMENT.fields_by_name['ref'].containing_oneof = _ELEMENT.oneofs_by_name['element_kind']
_ELEMENT.oneofs_by_name['element_kind'].fields.append(
  _ELEMENT.fields_by_name['text'])
_ELEMENT.fields_by_name['text'].containing_oneof = _ELEMENT.oneofs_by_name['element_kind']
_ELEMENT.oneofs_by_name['element_kind'].fields.append(
  _ELEMENT.fields_by_name['tag'])
_ELEMENT.fields_by_name['tag'].containing_oneof = _ELEMENT.oneofs_by_name['element_kind']
_PARTIALSERVERSTATE_ELEMENTSENTRY.fields_by_name['value'].message_type = _ELEMENT
_PARTIALSERVERSTATE_ELEMENTSENTRY.containing_type = _PARTIALSERVERSTATE
_PARTIALSERVERSTATE.fields_by_name['elements'].message_type = _PARTIALSERVERSTATE_ELEMENTSENTRY
_POLLRESPONSE.fields_by_name['state'].message_type = _PARTIALSERVERSTATE
_INTERACTION.fields_by_name['click'].message_type = _CLICKEVENT
_INTERACTION.fields_by_name['text_input'].message_type = _TEXTINPUTEVENT
_INTERACTION.oneofs_by_name['interaction_kind'].fields.append(
  _INTERACTION.fields_by_name['click'])
_INTERACTION.fields_by_name['click'].containing_oneof = _INTERACTION.oneofs_by_name['interaction_kind']
_INTERACTION.oneofs_by_name['interaction_kind'].fields.append(
  _INTERACTION.fields_by_name['text_input'])
_INTERACTION.fields_by_name['text_input'].containing_oneof = _INTERACTION.oneofs_by_name['interaction_kind']
_INTERACTIONREQUEST.fields_by_name['interaction'].message_type = _INTERACTION
DESCRIPTOR.message_types_by_name['Attributes'] = _ATTRIBUTES
DESCRIPTOR.message_types_by_name['Tag'] = _TAG
DESCRIPTOR.message_types_by_name['Element'] = _ELEMENT
DESCRIPTOR.message_types_by_name['PartialServerState'] = _PARTIALSERVERSTATE
DESCRIPTOR.message_types_by_name['PollRequest'] = _POLLREQUEST
DESCRIPTOR.message_types_by_name['PollResponse'] = _POLLRESPONSE
DESCRIPTOR.message_types_by_name['ClickEvent'] = _CLICKEVENT
DESCRIPTOR.message_types_by_name['TextInputEvent'] = _TEXTINPUTEVENT
DESCRIPTOR.message_types_by_name['Interaction'] = _INTERACTION
DESCRIPTOR.message_types_by_name['InteractionRequest'] = _INTERACTIONREQUEST
DESCRIPTOR.message_types_by_name['InteractionResponse'] = _INTERACTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Attributes = _reflection.GeneratedProtocolMessageType('Attributes', (_message.Message,), dict(

  MiscEntry = _reflection.GeneratedProtocolMessageType('MiscEntry', (_message.Message,), dict(
    DESCRIPTOR = _ATTRIBUTES_MISCENTRY,
    __module__ = 'protobuf.element_pb2'
    # @@protoc_insertion_point(class_scope:braggle.Attributes.MiscEntry)
    ))
  ,
  DESCRIPTOR = _ATTRIBUTES,
  __module__ = 'protobuf.element_pb2'
  # @@protoc_insertion_point(class_scope:braggle.Attributes)
  ))
_sym_db.RegisterMessage(Attributes)
_sym_db.RegisterMessage(Attributes.MiscEntry)

Tag = _reflection.GeneratedProtocolMessageType('Tag', (_message.Message,), dict(
  DESCRIPTOR = _TAG,
  __module__ = 'protobuf.element_pb2'
  # @@protoc_insertion_point(class_scope:braggle.Tag)
  ))
_sym_db.RegisterMessage(Tag)

Element = _reflection.GeneratedProtocolMessageType('Element', (_message.Message,), dict(
  DESCRIPTOR = _ELEMENT,
  __module__ = 'protobuf.element_pb2'
  # @@protoc_insertion_point(class_scope:braggle.Element)
  ))
_sym_db.RegisterMessage(Element)

PartialServerState = _reflection.GeneratedProtocolMessageType('PartialServerState', (_message.Message,), dict(

  ElementsEntry = _reflection.GeneratedProtocolMessageType('ElementsEntry', (_message.Message,), dict(
    DESCRIPTOR = _PARTIALSERVERSTATE_ELEMENTSENTRY,
    __module__ = 'protobuf.element_pb2'
    # @@protoc_insertion_point(class_scope:braggle.PartialServerState.ElementsEntry)
    ))
  ,
  DESCRIPTOR = _PARTIALSERVERSTATE,
  __module__ = 'protobuf.element_pb2'
  # @@protoc_insertion_point(class_scope:braggle.PartialServerState)
  ))
_sym_db.RegisterMessage(PartialServerState)
_sym_db.RegisterMessage(PartialServerState.ElementsEntry)

PollRequest = _reflection.GeneratedProtocolMessageType('PollRequest', (_message.Message,), dict(
  DESCRIPTOR = _POLLREQUEST,
  __module__ = 'protobuf.element_pb2'
  # @@protoc_insertion_point(class_scope:braggle.PollRequest)
  ))
_sym_db.RegisterMessage(PollRequest)

PollResponse = _reflection.GeneratedProtocolMessageType('PollResponse', (_message.Message,), dict(
  DESCRIPTOR = _POLLRESPONSE,
  __module__ = 'protobuf.element_pb2'
  # @@protoc_insertion_point(class_scope:braggle.PollResponse)
  ))
_sym_db.RegisterMessage(PollResponse)

ClickEvent = _reflection.GeneratedProtocolMessageType('ClickEvent', (_message.Message,), dict(
  DESCRIPTOR = _CLICKEVENT,
  __module__ = 'protobuf.element_pb2'
  # @@protoc_insertion_point(class_scope:braggle.ClickEvent)
  ))
_sym_db.RegisterMessage(ClickEvent)

TextInputEvent = _reflection.GeneratedProtocolMessageType('TextInputEvent', (_message.Message,), dict(
  DESCRIPTOR = _TEXTINPUTEVENT,
  __module__ = 'protobuf.element_pb2'
  # @@protoc_insertion_point(class_scope:braggle.TextInputEvent)
  ))
_sym_db.RegisterMessage(TextInputEvent)

Interaction = _reflection.GeneratedProtocolMessageType('Interaction', (_message.Message,), dict(
  DESCRIPTOR = _INTERACTION,
  __module__ = 'protobuf.element_pb2'
  # @@protoc_insertion_point(class_scope:braggle.Interaction)
  ))
_sym_db.RegisterMessage(Interaction)

InteractionRequest = _reflection.GeneratedProtocolMessageType('InteractionRequest', (_message.Message,), dict(
  DESCRIPTOR = _INTERACTIONREQUEST,
  __module__ = 'protobuf.element_pb2'
  # @@protoc_insertion_point(class_scope:braggle.InteractionRequest)
  ))
_sym_db.RegisterMessage(InteractionRequest)

InteractionResponse = _reflection.GeneratedProtocolMessageType('InteractionResponse', (_message.Message,), dict(
  DESCRIPTOR = _INTERACTIONRESPONSE,
  __module__ = 'protobuf.element_pb2'
  # @@protoc_insertion_point(class_scope:braggle.InteractionResponse)
  ))
_sym_db.RegisterMessage(InteractionResponse)


_ATTRIBUTES_MISCENTRY._options = None
_PARTIALSERVERSTATE_ELEMENTSENTRY._options = None
# @@protoc_insertion_point(module_scope)
